name: uBO Scope release

on:
  create:
    branches: master

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for creating release
    name: Build packages
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Get release information
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build packages
        run: |
          tools/make-chromium.sh ${{ env.VERSION }}
          tools/make-firefox.sh ${{ env.VERSION }}
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: true
          prerelease: true
          files: |
            build/uBlock0_${{ env.VERSION }}.chromium.zip
            build/uBlock0_${{ env.VERSION }}.firefox.xpi
